# Generated by Django 4.0 on 2021-12-19 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_messages_options_messages_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={},
        ),
        migrations.RemoveField(
            model_name='messages',
            name='timestamp',
        ),
    ]
